# add_newline = true
# # A minimal left prompt
# format = """
# $directory$character
# """
palette = "catppuccin_mocha"
# # move the rest of the prompt to the right
right_format = """[$all]($style)"""
# right_format = 'hello'

command_timeout = 1000

# [git_branch]
# disabled = true
# [git_status]
# disabled = true
# [git_metrics]
# disabled = true
# [git_state]
# disabled = true
# [git_commit]
# disabled = true



[nodejs]
disabled = true

[username]
disabled = true

[hostname]
format = '[$hostname]($style)'
disabled = true

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[container]
disabled = true

[git_branch]
format =  '[$branch(:$remote_branch)]($style)'
disabled = true

[docker_context]
# disabled = true
format = '[$symbol]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

